version: '3'

services:
    toky-finance-service:
        build: .
        ports:
            - "3001:3001"
            - "3003:3003"
        environment: 
            - DB_NAME=tokyfinance
            - DB_PASS=pwd
            - DB_USER=tokyuser
            - DB_TYPE=postgres
            - DB_HOST=localhost
            - DB_PORT=5432
            - USER_BATCH_PORT=3003
            - OPENID_JWKS_URL=http://localhost:8080/auth/realms/toky-finance/protocol/openid-connect/certs
        network_mode: "host"
    user-batch:
        image: toky03/user-batch
        environment:
            - INTERVAL_SECONDS=10
            - ID_PROVIDER_ENDPOINT=http://localhost:8080/auth/admin/realms/toky-finance/users
            - ID_PROVIDER_ACCESS_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJvUXFmUEwxU2s5STFuNGdScWVLaHNWa1VZNklDRGRvejN2OWdUOExBcGFzIn0.eyJleHAiOjE1OTk0MjUwMTUsImlhdCI6MTU5OTM4OTAxNSwianRpIjoiZmU1MTEwZDctMjQ1MC00OGQ0LWI0Y2QtNDAwMjkwODU1Y2E5IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL3Rva3ktZmluYW5jZSIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiJjNTljOGE3ZC0yMGZjLTRhY2YtOTNlNi05ODg3MTdlNmY1MmYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ0b2t5LWZpbmFuY2Utc2VydmljZSIsInNlc3Npb25fc3RhdGUiOiJjNGY1YWJlMS03MGEyLTQ3MjYtYjUwNi1kYjhmZWNlNGZjNjIiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidmlldy11c2VycyIsInVtYV9hdXRob3JpemF0aW9uIiwicXVlcnktdXNlcnMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwidG9reS1maW5hbmNlLXNlcnZpY2UiOnsicm9sZXMiOlsidmlldy11c2VycyJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkZpbmFuY2UgU2VydmljZSBBUEkgVXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6ImZpbmFuY2Utc2VydmljZSIsImdpdmVuX25hbWUiOiJGaW5hbmNlIFNlcnZpY2UgQVBJIFVzZXIifQ.aYqo9Lyt30km0cSEOsPEanFD9fOsisY9Yra9wNYdf1nLMvq4udpXjwumOEG6Qo0dS7J9w37AHkQFdlPikVAm5X0euLvF0Nm6TVWcWCWOGoI5ih3zfie4TNzItVAnGMHnzlK1eFmvASKQDB9gGSLfVFGbhtIKSCwt-T5cdVJ2kBef71nT132-OAdoJYKM45gkIyDi6CJHOSs1lnHTKqF9pEF5OuHdB1vSCgZAoMm0Ibpv1nCB5Xrxjurm4t2zM4jkwQaLrWFfIsZpnYYRsAbzNY1n2GdK1QQPPhWZncz0NpcZSnQ6tWI5efwwMQlPrxDALsNaQsA00Ya2NupeUJ2AEg
            - ACCOUNTING_SERVER_ENDPOINT=localhost:3003
        depends_on:
            - toky-finance-service
        network_mode: "host"
#     finance-db:
#         image: postgres:9.6
# #        ports:
#         #- "5454:5432"
#         environment: 
#             - POSTGRES_DB=tokyfinance
#             - POSTGRES_PASSWORD=pwd
#             - POSTGRES_USER=tokyuser
