version: '3'

services:
    toky-finance-service:
        build: .
        ports:
            - "3001:3001"
            - "3003:3003"
        environment: 
            - DB_NAME=tokyfinance
            - DB_PASS=pwd
            - DB_USER=tokyuser
            - DB_TYPE=postgres
            - DB_HOST=localhost
            - DB_PORT=5432
            - USER_BATCH_PORT=3003
            - OPENID_JWKS_URL=http://localhost:8080/auth/realms/toky-finance/protocol/openid-connect/certs
        network_mode: "host"
    user-batch:
        image: toky03/user-batch
        environment:
            - INTERVAL_SECONDS=10
            - ID_PROVIDER_ENDPOINT=http://localhost:8080/auth/admin/realms/toky-finance/users
            - ID_PROVIDER_ACCESS_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJvUXFmUEwxU2s5STFuNGdScWVLaHNWa1VZNklDRGRvejN2OWdUOExBcGFzIn0.eyJleHAiOjE1OTk0NDgwOTQsImlhdCI6MTU5OTQxMjA5NCwianRpIjoiMjkyOWRmZTYtOGZmMC00MWNkLTkyYmMtNzMxYzQ5ODU4YmJmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2F1dGgvcmVhbG1zL3Rva3ktZmluYW5jZSIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYWNjb3VudCJdLCJzdWIiOiJjNTljOGE3ZC0yMGZjLTRhY2YtOTNlNi05ODg3MTdlNmY1MmYiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJ0b2t5LWZpbmFuY2Utc2VydmljZSIsInNlc3Npb25fc3RhdGUiOiI2YmQ3N2E2OC02OWYzLTQ3NjMtOGFjNS0wMjcwMjliZWI2YTMiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidmlldy11c2VycyIsInVtYV9hdXRob3JpemF0aW9uIiwicXVlcnktdXNlcnMiXX0sInJlc291cmNlX2FjY2VzcyI6eyJyZWFsbS1tYW5hZ2VtZW50Ijp7InJvbGVzIjpbInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwidmlldy1yZWFsbSIsIm1hbmFnZS1pZGVudGl0eS1wcm92aWRlcnMiLCJpbXBlcnNvbmF0aW9uIiwicmVhbG0tYWRtaW4iLCJjcmVhdGUtY2xpZW50IiwibWFuYWdlLXVzZXJzIiwicXVlcnktcmVhbG1zIiwidmlldy1hdXRob3JpemF0aW9uIiwicXVlcnktY2xpZW50cyIsInF1ZXJ5LXVzZXJzIiwibWFuYWdlLWV2ZW50cyIsIm1hbmFnZS1yZWFsbSIsInZpZXctZXZlbnRzIiwidmlldy11c2VycyIsInZpZXctY2xpZW50cyIsIm1hbmFnZS1hdXRob3JpemF0aW9uIiwibWFuYWdlLWNsaWVudHMiLCJxdWVyeS1ncm91cHMiXX0sImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfSwidG9reS1maW5hbmNlLXNlcnZpY2UiOnsicm9sZXMiOlsidmlldy11c2VycyJdfX0sInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkZpbmFuY2UgU2VydmljZSBBUEkgVXNlciIsInByZWZlcnJlZF91c2VybmFtZSI6ImZpbmFuY2Utc2VydmljZSIsImdpdmVuX25hbWUiOiJGaW5hbmNlIFNlcnZpY2UgQVBJIFVzZXIifQ.cLq0Jl_47-GWdaNG5R6m5kEKo_C_9LuEumiimXitEOgzrW3OKHjTllOG6moTSuyOYfiDrpHl8u3W9-qvztHORnDHehGe_k1yjXAZTplBLLaqO7sFI6WeWwngx5j1E84rPmy8cLD2HdwKWv_tRqfB6jz3AUJJC1vnWsspUfYp76LbFCLB23_y1N-rX7VLzv7tbyjZHbkqdiD5dLsTGeGj9dByVW9ZPGj70yzr0ccueYg2eduTlOwZGJ_u5jub38GAizC-NgSxgEBfwbWSI9NGrLAUyKZc0V5YBESgNe3v_3oILYiu4BAqDHZ_UO-IDtW6paLjMXQw10Y1dYqyrCVQQw
            - ACCOUNTING_SERVER_ENDPOINT=localhost:3003
        depends_on:
            - toky-finance-service
        network_mode: "host"
#     finance-db:
#         image: postgres:9.6
# #        ports:
#         #- "5454:5432"
#         environment: 
#             - POSTGRES_DB=tokyfinance
#             - POSTGRES_PASSWORD=pwd
#             - POSTGRES_USER=tokyuser
