version: '3'

services:
    toky-finance-service:
        build: .
        ports:
            - "3001:3001"
            - "3003:3003"
        environment: 
            - DB_NAME=tokyfinance
            - DB_PASS=pwd
            - DB_USER=tokyuser
            - DB_TYPE=postgres
            - DB_HOST=localhost
            - DB_PORT=5432
            - USER_BATCH_PORT=3003
            - OPENID_JWKS_URL=http://localhost:8080/auth/realms/toky-finance/protocol/openid-connect/certs
        network_mode: "host"
    user-batch:
        image: toky03/user-batch:0.0.1
        environment:
            - INTERVAL_SECONDS=10
            - ID_PROVIDER_ENDPOINT=http://localhost:8080/auth/admin/realms/toky-finance/users
            - ACCOUNTING_SERVER_ENDPOINT=localhost:3003
            - ID_PROVIDER_TOKEN_ENDPOINT=http://localhost:8080/auth/realms/toky-finance/protocol/openid-connect/token
            - ID_PROVIDER_USERNAME=finance-service
            - ID_PROVIDER_PASSWORD=admin
            - ID_PROVIDER_CLIENT_SECRET=46dd09e3-19f6-457d-8ec3-0ea0264cefde
            - ID_PROVIDER_CLIENT_ID=toky-finance-service
        depends_on:
            - toky-finance-service
        network_mode: "host"
#     finance-db:
#         image: postgres:9.6
# #        ports:
#         #- "5454:5432"
#         environment: 
#             - POSTGRES_DB=tokyfinance
#             - POSTGRES_PASSWORD=pwd
#             - POSTGRES_USER=tokyuser
