version: '3'

services:
    toky-finance-service:
        build: .
        depends_on: finance-db
        ports:
            - "8080:8080"
        environment: 
            - DB_NAME=tokyfinance
            - DB_PASS=pwd
            - DB_USER=tokyuser
            - DB_TYPE=postgres
            - DB_HOST=finance-db
            - DB_PORT=5432
    finance-db:
        image: postgres:9.6
        ports:
        #- "5454:5432"
        environment: 
        - POSTGRES_DB=tokyfinance
        - POSTGRES_PASSWORD=pwd
        - POSTGRES_USER=tokyuser