version: '3'

volumes:
    finance_data:
        driver: local
    keycloak_data:
        driver: local
    theme:
        driver: local

services:
    financedb:
        image: postgres:15-alpine
        environment: 
            - POSTGRES_DB=tokyfinance
            - POSTGRES_PASSWORD=pwd
            - POSTGRES_USER=tokyuser
    toky-finance-service:
        build: .
        ports:
            - "3001:3001"
            - "3003:3003"
        environment: 
            - DB_NAME=tokyfinance
            - DB_PASS=pwd
            - DB_USER=tokyuser
            - DB_TYPE=postgres
            - DB_HOST=financedb
            - DB_PORT=5432
            - USER_BATCH_PORT=3003
            - OPENID_JWKS_URL=http://keycloak-service:8080/realms/SimpleAccounting/protocol/openid-connect
            - OPENID_JWKS_EXTERNAL_URL=http://localhost:8080/realms/SimpleAccounting/protocol/openid-connect
            - USER_BATCH_TRIGGER_ENDPOINT=http://user-batch:3005/triggerBatchRun
            - ID_PROVIDER_CLIENT_SECRET=PcmHZhknfDoEsOvkYDpejvmrdL3yW41A
            - ID_PROVIDER_CLIENT_ID=toky-accounting
        depends_on:
            - keycloak-service
            - financedb
    user-batch:
        image: toky03/user-batch:1.0.0
        environment:
            - REST_PORT=3005
            - INTERVAL_SECONDS=10
            - ID_PROVIDER_ENDPOINT=http://keycloak-service:8080/admin/realms/SimpleAccounting/users
            - ACCOUNTING_SERVER_ENDPOINT=toky-finance-service:3003
            - ID_PROVIDER_TOKEN_ENDPOINT=http://keycloak-service:8080/realms/SimpleAccounting/protocol/openid-connect/token
            - ID_PROVIDER_USERNAME=finance-service
            - ID_PROVIDER_PASSWORD=admin
            - ID_PROVIDER_CLIENT_SECRET=PcmHZhknfDoEsOvkYDpejvmrdL3yW41A
            - ID_PROVIDER_CLIENT_ID=toky-accounting
        depends_on:
            - toky-finance-service
        ports:
            - "3005:3005"
    keycloak-db:
        image: postgres
        volumes:
            - keycloak_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak_db
            POSTGRES_USER: kc_user
            POSTGRES_PASSWORD: kc_password
    keycloak-service:
        image: toky03/keycloak-finance
        environment:
            - KEYCLOAK_ADMIN=admin
            - KEYCLOAK_ADMIN_PASSWORD=admin
            - KC_DB=postgres
            - KC_DB_USERNAME=kc_user
            - DB_SCHEMA=public
            - KC_DB_PASSWORD=kc_password
            - PROXY_ADDRESS_FORWARDING=true
            - KC_DB_SCHEMA=public
            - KC_DB_URL_DATABASE=keycloak_db
            - KC_DB_URL_HOST=keycloak-db
            - KC_DB_URL_PORT=5432
            - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak_db?ssl=allow
            - WEBHOOK_URL=http://user-batch:3005/triggerBatchRun
        ports: 
            - 8080:8080
        volumes: 
            - ./keycloak/custom-theme:/opt/keycloak/themes/toky-keycloak-theme
            - ./keycloak/config:/opt/keycloak/data/import
        depends_on: 
            - keycloak-db
