version: '3'

volumes:
    postgres_data:
        driver: local
    theme:
        driver: local
            
services:
    postgres:
        image: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak_db
            POSTGRES_USER: kc_user
            POSTGRES_PASSWORD: kc_password

    keycloak-service:
        image: toky03/keycloak
        environment: 
            - KEYCLOAK_USER=admin
            - KEYCLOAK_PASSWORD=admin
            - DB_VENDOR=postgres
            - DB_ADDR=postgres
            - DB_DATABASE=keycloak_db
            - DB_USER=kc_user
            - DB_SCHEMA=public
            - DB_PASSWORD=kc_password
            - PROXY_ADDRESS_FORWARDING=true
        ports: 
            - 8080:8080
        volumes: 
            - ./custom-theme:/opt/jboss/keycloak/themes/toky-keycloak-theme
        depends_on: 
            - postgres